### ISSUE TITLE
增设招新板块

### ISSUE THREAD

**Issue by ComMouse** [dyweb/dyweb.github.io#11]
现有的合作咨询板块相对而言作用不是很大，由于该页面更多用作招新宣传，修改为招新板块相对而言更加好一些。

一个初步的计划是，将该板块的按钮改为 “加入我们”，同时修改上一行的文字描述；四种开发类型改为 ”Website", "Android App", "iOS App", "Product"（对应原来的四个图标）。

假如可行的话，可以尝试一版看看效果。

希望各位可以给出参考意见。@gaocegege @at15 @arrowrowe  @rudeigerc @vinx13 @hebingchang

**Comment by at15** [comment]
感觉可以把合作咨询放到 footer 里，像红帽一样....

![image](https://user-images.githubusercontent.com/5621298/32309820-6c094010-bf4b-11e7-834f-4badc29118ac.png)

from https://www.ansible.com/ (ansbile 居然是被红帽买了....

**Comment by ComMouse** [comment]
@at15 感觉好像没有这么多内容可以写 =w=

**Comment by gaocegege** [comment]
我觉得 OK

**Comment by at15** [comment]
@ComMouse 起码放上 GitHub 的链接 /w

**Comment by arrowrowe** [comment]
zici
