### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by ComMouse** [dyweb/dyweb.github.io#13]
Just for private purpose to demonstrate our orginzation.

Now considering two implementation methods: via i18n lib or maintaining two versions.

Since it is not important at present, l'll leave the issue here for further reference.

**Comment by at15** [comment]
hmm, since you will be applying for school? I guess both should be ok, you can detect lang and redirect to the English version, I prefer having a standalone English version

**Comment by ComMouse** [comment]
[A simple version for trial](http://dongyueweb.com/index-en-US.html)

Please ignore some strange translations =0=

**Comment by at15** [comment]
LGTM

![LGTM](https://media.giphy.com/media/zJjNEhlW3gQx2/giphy-downsized-large.gif)

**Comment by at15** [comment]
.... some words are wired, anyway, people won't look at them carefully

**Comment by ComMouse** [comment]
Better translations are welcome since these words are just randomly selected= =
