### ISSUE TITLE
新版东岳主页

### ISSUE THREAD

**Issue by at15** [dyweb/dyweb.github.io#4]
之前有重新设计过的主页, 不过一直是private了, 后面放到 gitlab里了 

http://git.tongqu.me/dy/homepage

**Comment by tq5124** [comment]
那个只是设计稿？

**Comment by at15** [comment]
@tq5124 已经实现了一部分了 @arrowrowe  但是因为我们几个都懒(其实把xbox的时间剩下1/10...) so...

**Comment by tq5124** [comment]
对了，xbox上有2k16嘛！我圣诞回来！~

**Comment by at15** [comment]
@tq5124 你想玩的话我们可以买一下...毕竟一个游戏才300, 考虑到一餐吃一天都要50, 游戏简直是白菜价。现在运动类的只有实况和fifa的2014&2016 另外就是刺客信条全家桶, 光环全家桶, 战地4, 赛车, 跳舞, 弱智兔子, 体感游戏 x 3, 还有好几个买回来就没安过的fps.... (为何这么浪费...难道喜欢fps的只有我一个....)

**Comment by tq5124** [comment]
没有就不要买了。。。反正圣诞回来聚~

**Comment by utf8please** [comment]
圣诞一起来玩吧，我这边应该也可以回去～

**Comment by tq5124** [comment]
好~

**Comment by LukeXuan** [comment]
所以我能吐槽 不应该是讨论新版主页的吗（

**Comment by at15** [comment]
@LukeXuan .... ( @tq5124 有学弟想买2k 我看看能再凑几个人, 前几天买的刺客信条寄了个ps4版的过来刚寄回去

**Comment by LukeXuan** [comment]
@at15 我不玩2k……体育类都不怎么玩

**Comment by at15** [comment]
@LukeXuan 推黄油么? @kdplus (越来越歪了.....

**Comment by LukeXuan** [comment]
@at15 以前推 不过有xbox的黄油么（

**Comment by kdplus** [comment]
@at15 我其实没推过几个黄油

**Comment by at15** [comment]
@tq5124 xbox 金会员有了免费的2k16, 但是很奇怪, 叫免费游戏日, 可能只能玩一段时间

**Comment by arrowrowe** [comment]
话说现在主页已经差不多了。。。样式细节要微调，内容要填上。。

**Comment by ComMouse** [comment]
最近能上吗。。。@arrowrowe

**Comment by at15** [comment]
@ComMouse 咩还在依图搬砖吧....?

**Comment by arrowrowe** [comment]
......@ComMouse 要不你看两眼?

**Comment by ComMouse** [comment]
😭

**Comment by kdplus** [comment]
好古老...

**Comment by at15** [comment]
some inspiration https://www.instacart.com/opensource

**Comment by at15** [comment]
赞美小豆(当别人在讨论妹子的问题时候豆在默默干活) 👍
